apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ${gitops_apps_repo_url}/crds/${deploy_name}?ref=${gitops_apps_repo_branch}
patches:
  - target:
      kind: HelmRelease
      name: ${deploy_name}
      namespace: flux-system
    patch: |-
      - op: replace
        path: /spec/chart/spec/version
        value: "${chart_version}"
