---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cluster-reconciler-${deploy_name}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
  - kind: ServiceAccount
    name: helm-controller
    namespace: "trivy-system"
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: ${app_install_name}-helm
  namespace: flux-system
spec:
  serviceAccountName: kustomize-controller
  interval: 1m0s
  dependsOn:
    - name: platform-apps-sources
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: "./${helm_repo_path}"
  prune: ${prune}
  postBuild:
    substitute:
      flux_cluster_name: ${cluster_name}
      flux_trivy_operator_cpu: ${resources_requests_cpu}
      flux_trivy_operator_memory: ${resources_requests_memory}
      flux_trivy_operator_scan_jobs_cpu: ${scan_resources_requests_cpu}
      flux_trivy_operator_scan_jobs_memory: ${scan_resources_requests_memory}
      flux_workload_account_id: "${workload_account_id}"
