apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ${gitops_apps_repo_url}/apps/${deploy_name}?ref=${gitops_apps_repo_ref}
patches:
  - target:
      kind: HelmRelease
      name: goldpinger
      namespace: goldpinger
    patch: |-
      - op: replace
        path: /spec/chart/spec/version
        value: "${chart_version}"
