---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cluster-reconciler-${deploy_name}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
  - kind: ServiceAccount
    name: helm-controller
    namespace: atlantis
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: ${app_install_name}-helm
  namespace: flux-system
spec:
  serviceAccountName: kustomize-controller
  interval: 1m0s
  dependsOn:
    - name: platform-apps-sources
    - name: platform-apps-external-secrets-helm
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: "./${helm_repo_path}"
  prune: ${prune}
  postBuild:
    substitute:
      flux_atlantis_resource_cpu: ${resource_cpu}
      flux_atlantis_resource_memory: ${resource_memory}
      flux_cluster_name: ${cluster_name}
      flux_workload_account_id: "${workload_account_id}"
      flux_eks_fqdn: ${eks_fqdn}
